services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: imagen-aplicas:latest
    container_name: aplicas-container
    ports:
      - "8089:3000"
    env_file:
      - .env
    depends_on: []
    restart: unless-stopped
